FROM openjdk:8

MAINTAINER zh

LABEL name="dockerfile-demo" version="1.0" author="jack"

COPY springboot-docker-test-1.0-SNAPSHOT.jar dockerfile-image.jar

CMD ["java", "-jar", "dockerfile-image.jar"]
